### ISSUE TITLE
Contrast should be an integer field, not a slider

### ISSUE THREAD

**Issue by rpdelaney** [NicoKandut/factorio-solar-art#12]
I'm trying to generate a set of solar blue prints for a chess board. If I could just enter a number then I could note down the settings I used and come back to iterate on it if I decide I don't like how it looks later.

**Comment by NicoKandut** [comment]
It can be both

**Comment by NicoKandut** [comment]
This is included in the latest release. You can use both the slider and the number to set the contrast value now. Let me know what you think.

**Comment by rpdelaney** [comment]
It seems your instance at https://nicokandut.github.io/factorio-solar-art/ hasn't updated yet? I'm comfortable in a teminal, but I'm not much of a web dev; are there installation instructions for getting it going locally?

**Comment by NicoKandut** [comment]
Ctrl + F5 (force reload) should do the trick. Otherwise just close all tabs of the app and open it again.

**Comment by rpdelaney** [comment]
Got it. This should work well for me :) Thanks!
