### ISSUE TITLE
Feature request: dectorio support

### ISSUE THREAD

**Issue by rpdelaney** [NicoKandut/factorio-solar-art#13]
[Dectorio](https://mods.factorio.com/mod/Dectorio) adds a lot of turf types that render colorfully on the map. 

What I love about this app is that I can use it build solar arrays that are both artistic _and_ functional. However, sometimes you need a useless structure to complete the visual effect, as this app shows already by using walls and refined concrete.

Is there room to integrate some of these turfs into factorio-solar-art?

Alternatively, could the concepts in factorio-solar-art be applied to make colored pixel art that is not functional but more aesthetically consistent with the original art?

**Comment by NicoKandut** [comment]
I think the second option makes more sense here. Instead of smashing more stuff into this app we could build a dedicated one for pixel art. That way we can ensure both stay great and neither one has to compromise because of the other one.

What do you think?

**Comment by rpdelaney** [comment]
That makes sense to me yeah. Since solar art only uses concrete to fill gaps between substations and other entities, there isn't much room for adding color there.

If you're feeling inspired to apply this logic to a turf-only app I would be happy to help however I can. We can talk more about it on your discord now that I'm there :-)
