### ISSUE TITLE
Only reload after settings lose focus

### ISSUE THREAD

**Issue by NicoKandut** [NicoKandut/factorio-solar-art#5]

**Comment by rpdelaney** [comment]
Related: don't rebuild the blueprint for every key-stroke if I change its name after rendering :)

**Comment by NicoKandut** [comment]
Decided to go for a "render after input loses focus" approach. It's a middle ground between rendering each change and render only once after all settings have been set.

@rpdelaney Implemented your suggestion as well. Changing the name will no longer rerender the blueprint.
