### ISSUE TITLE
Improve brightness (luminescence) calculation

### ISSUE THREAD

**Issue by msarchet** [NicoKandut/factorio-solar-art#9]
Was looking at your code in how you calculate brightness. R+G+B/255/3 isn't accurate as to how humans perceive luminescence. A more accurate formula is as follows.

L=0.2126*R_+0.7152*G_+0.0722*B from [Relative Luminance](https://en.wikipedia.org/wiki/Relative_luminance)

Happy to make an attempt at this change and go through some comparison of the results.

**Comment by NicoKandut** [comment]
Nice! Good work man.
